name: Create Extension Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-package-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create source.zip for firefox store
        run: zip -r source.zip .

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Build the extension with rslib
        run: npm run build

      - name: Package the extension
        run: zip -r youtube-better-ambient.zip manifest.json icons dist/index.js

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: youtube-better-ambient.zip
      
      - uses: browser-actions/release-firefox-addon@latest
        with:
          addon-id: "pr0verter@gmail.com"
          addon-path: "youtube-better-ambient.zip"
          source-path: "source.zip"
          approval-note: |
            The source project requires Node.js 20.x and npm.
            To generate the source code, please run "npm run build"
          auth-api-issuer: ${{ secrets.AUTH_API_ISSUER }}
          auth-api-secret: ${{ secrets.AUTH_API_SECRET }}